### ISSUE TITLE
Can your share the wifi driver  pls~

### ISSUE THREAD

**Issue by CatSamaDD** [Greg798100/Orangepi-r1-openwrt#4]
I can use wifi with your 22.03.5 firmware.
But I can't install docker
Even I edit the /usr/lib/opkg/status to fix the kernel compatibility issues
the network will crash when I intsall dockerd use opkg.

Can you help me pls..
![1](https://github.com/Greg798100/Orangepi-r1-openwrt/assets/34727840/956188a8-4223-4d83-9c31-70e4ddeceb82)

**Comment by Greg798100** [comment]
HI @CatSamaDD 
```
git clone https://github.com/Greg798100/rtl8189es.git
cd rtl8189es
git branch -a
git checkout origin/openwrt-22.03.5
```
Im not used docker, but openwrt-21.02.6 worked, and stably. I recommend to try it.
You can download _https://github.com/openwrt/openwrt/releases/tag/v21.02.6_ and _https://github.com/immortalwrt/immortalwrt/releases/tag/v21.02.6_
Copy _immortalwrt/package/kernel/mac80211_  and _immortalwrt/package/kernel/rtl8189es_ to orig openwrt-21.02.6 source and make.
